//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchoolDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedStudent
    {
        public int AssignedStudentID { get; set; }
        public int DriverID { get; set; }
        public int StudentID { get; set; }
    
        public virtual DriverInfo DriverInfo { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
