//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchoolDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonID { get; set; }
        public int StudentID { get; set; }
        public int DriverID { get; set; }
        public int CategoryID { get; set; }
        public int VehicleID { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public System.DateTime LessonDateTime { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Student Student { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
