//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchoolDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonID { get; set; }
        public int StudentID { get; set; }
        public int DriverID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LessonDate { get; set; }
        public int LessonTimeID { get; set; }
    
        public virtual DriverInfo DriverInfo { get; set; }
        public virtual LessonTime LessonTime { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
