//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchoolDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int ManagerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public int UserTypeID { get; set; }
        public string About { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AddressID { get; set; }
        public int UserCredentialID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual UserCredential UserCredential { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
