//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchoolDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int PasswordID { get; set; }
        public int UserID { get; set; }
        public string PasswordHash { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
