//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchoolDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public int PermissionTemplateID { get; set; }
        public int UserTypeID { get; set; }
        public bool Access { get; set; }
    
        public virtual PermissionTemplate PermissionTemplate { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
